export { default as Blog } from './blog/Blog'
export { default as Features } from './features/Features'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as QuiSom } from './quisom/QuiSom'
export { default as Allies } from './allies/Allies'